### ISSUE TITLE
Class TwigBridge\Twig\Loader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSourceContext)

### ISSUE THREAD

**Issue by enchance** [rcrowe/TwigBridge#300] opened 2017-01-06 17:19 UTC
Just made a fresh install of Laravel 5.3 and I'm getting the error `Class TwigBridge\Twig\Loader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSourceContext)`. This comes out whether the file *testing.twig* contains a variable or not.
![screenshot from 2017-01-07 01-11-28](https://cloud.githubusercontent.com/assets/1474866/21726318/405e55d2-d477-11e6-9bf7-03ffe1a75e22.png)

**Comment by GrahamCampbell** [comment] 2017-01-06 17:21
Duplicate of https://github.com/rcrowe/TwigBridge/issues/298.

**Comment by enchance** [comment] 2017-01-06 17:40
@GrahamCampbell I didn't see that. I ended up locking my version to `v1.30.x` as well and it worked. I guess once a patch is released only then can we see if `v2.0` works now.

**Comment by GrahamCampbell** [comment] 2017-01-06 19:54
:)

**Closed by GrahamCampbell** 2017-01-06 19:54 UTC
