### ISSUE TITLE
twig lumen

### ISSUE THREAD

**Issue by carlofraue79** [rcrowe/TwigBridge#338] opened 2018-03-13 16:36 UTC
Hi,
anyone has test the solution with Lumen (5.6.2) (Laravel Components 5.6.*).
i have install it but i have recevied an error when use the function asset from template Twig_Error_Syntax
Unknown "asset" function in "login.twig".Have you found the issue or mismatch configuration.
Futhermore on twigbridge i have create the extension's array filled in this way.
      'enabled' => [
            'TwigBridge\Extension\Loader\Facades',
            'TwigBridge\Extension\Loader\Filters',
            'TwigBridge\Extension\Loader\Functions',

            //'TwigBridge\Extension\Laravel\Auth',
            'TwigBridge\Extension\Laravel\Config',
            'TwigBridge\Extension\Laravel\Dump',
            'TwigBridge\Extension\Laravel\Input',
            //'TwigBridge\Extension\Laravel\Session',
            'TwigBridge\Extension\Laravel\Str',
           // 'TwigBridge\Extension\Laravel\Translator',
           // 'TwigBridge\Extension\Laravel\Url',
            // 'TwigBridge\Extension\Laravel\Gate',

            // 'TwigBridge\Extension\Laravel\Form',
            // 'TwigBridge\Extension\Laravel\Html',
            // 'TwigBridge\Extension\Laravel\Legacy\Facades',
        ],

**Comment by svenluijten** [comment] 2018-03-15 16:01
Lumen is not typically used for apps that have views and/or output HTML. You could require `twig/twig` and wire up the templating yourself, but it'll be a lot easier to use the full Laravel framework in combination with this package 🙂

**Comment by carlofraue79** [comment] 2018-03-15 16:31
more more very in this case i have use laravel framework and after  i will include lumen for four api expose.
many thanks.

**Comment by svenluijten** [comment] 2018-03-16 08:16
You can close this issue if the problem is solved/no more action is required by the package author 🙂

**Closed** 2018-03-16 09:21 UTC
